
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=smn15031950
quarkus.hibernate-orm.dialect=org.hibernate.dialect.SQLServerDialect
quarkus.datasource.jdbc.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=OSCLI35;integratedSecurity=false;encrypt=false;trustServerCertificate=true;
quarkus.hibernate-orm.database.generation=update

quarkus.datasource.jdbc.max-size=200
quarkus.datasource.jdbc.min-size=20
quarkus.datasource.jdbc.query-timeout=300

quarkus.datasource.jdbc.idle-removal-interval=10
quarkus.datasource.jdbc.background-validation-interval=60

quarkus.hibernate-orm.query.plan-cache-max-size=512
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql.BasicBinder".level=TRACE
quarkus.http.host=0.0.0.0

hibernate.hbm2ddl.auto=validate



# Transação
quarkus.transaction-manager.timeout=300

# Habilita o log das consultas SQL geradas pelo Hibernate
quarkus.hibernate-orm.log.sql=true

# Habilita o log dos parâmetros das consultas SQL
quarkus.hibernate-orm.log.bind-parameters=true

# Configurações do servidor
quarkus.http.port=8085
quarkus.http.cors=true
quarkus.http.cors.origins=*