
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:raiox123}
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://127.0.0.1:5433/simplificasud}
quarkus.hibernate-orm.database.generation=update

quarkus.datasource.jdbc.max-size=200
quarkus.datasource.jdbc.min-size=20
quarkus.datasource.jdbc.query-timeout=300

quarkus.datasource.jdbc.idle-removal-interval=10
quarkus.datasource.jdbc.background-validation-interval=60

quarkus.hibernate-orm.query.plan-cache-max-size=512
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql.BasicBinder".level=TRACE
quarkus.http.host=0.0.0.0

hibernate.hbm2ddl.auto=validate



# Transa��o
quarkus.transaction-manager.timeout=300

# Habilita o log das consultas SQL geradas pelo Hibernate
quarkus.hibernate-orm.log.sql=true

# Habilita o log dos par�metros das consultas SQL
quarkus.hibernate-orm.log.bind-parameters=true

# Configura��es do servidor
quarkus.http.port=${PORT:8085}
quarkus.http.cors=true
quarkus.http.cors.origins=*