
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=smn15031950
quarkus.hibernate-orm.dialect=org.hibernate.dialect.SQLServerDialect
quarkus.datasource.jdbc.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=OSCLI32;integratedSecurity=false;encrypt=false;trustServerCertificate=true;
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.jdbc.max-size=16



# Caminho para a documentação OpenAPI
quarkus.smallrye-openapi.path=/q/openapi

# Caminho para o Swagger UI
quarkus.swagger-ui.path=/q/swagger-ui

# Habilita o log das consultas SQL geradas pelo Hibernate
quarkus.hibernate-orm.log.sql=true

# Habilita o log dos parâmetros das consultas SQL
quarkus.hibernate-orm.log.bind-parameters=true

# Configurações do servidor
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*